apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nanny
  name: nanny
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanny
  template:
    metadata:
      labels:
        app: nanny
    spec:
      imagePullSecrets:
      - name: awsecr-cred 
      containers:
      - name: nanny
        image: 064106913348.dkr.ecr.us-west-2.amazonaws.com/feed/nanny:0.1.8
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: FLASK_PORT
          valueFrom:
            configMapKeyRef:
              key: FLASK_PORT
              name: {{ .Values.environment }}
        - name: LOG_LEVEL
          value: "INFO"
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MONGO_HOST
              name: {{ .Values.environment }}
        - name: MONGO_PASS
          valueFrom:
            configMapKeyRef:
              key: MONGO_PASS
              name: feedmachine-env
        - name: MONGO_USER
          valueFrom:
            configMapKeyRef:
              key: MONGO_USER
              name: feedmachine-env
        - name: ROUTER_HOST
          valueFrom:
            configMapKeyRef:
              key: ROUTER_HOST
              name: feedmachine-env
        - name: UISERVER_HOST
          valueFrom:
            configMapKeyRef:
              key: UISERVER_HOST
              name: feedmachine-env
        - name: NANNY_HOST
          valueFrom:
            configMapKeyRef:
              key: FLASK_HOST
              name: feedmachine-env

        resources: {}
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: nanny
  labels:
    service: nanny
spec:
  selector:
    app: nanny
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
