environment: uat
feedAdminHostname: uatfeedmachine:30000
feedAdminServicePort: "30000"
leaderReplicas: 1
feedAdminReplicas: 1
captureCrawlerReplicas: 1
summarizerReplicas: 1
nannyReplicas: 1
routerReplicas: 1
uiServerReplicas: 1

mongoUser: uat_feeds
mongoPassword: uat_feeds_123

imageRepository: 064106913348.dkr.ecr.us-west-2.amazonaws.com

databaseUser: feeds
databasePass: feeds
databaseName: uat_feeds

crawler:
  healthCheckMethod: curl
  healthCheckEndpoint: http://localhost:444/wd/hub/status



