environment: uat
feedAdminHostname: uatfeedmachine:30000
feedAdminServicePort: "30000"
leaderReplicas: 1
feedAdminReplicas: 1
captureCrawlerReplicas: 1
summarizerReplicas: 1
nannyReplicas: 1
routerReplicas: 1
uiServerReplicas: 1

mongoUser: uat_feeds
mongoPassword: uat_feeds_123

uiServerVersion: feed/ui-server:0.1.0
nannyVersion: feed/nanny:0.1.8
leaderVersion: feed/leader:0.2.8
routerVersion: feed/routing:0.1.1
summarizerVersion: feed/summarizer:0.1.0
feedAdminVersion: feed/feed-admin:0.2.2
captureCrawlerVersion: feed/capture-crawler:0.1.9
imageRepository: 064106913348.dkr.ecr.us-west-2.amazonaws.com

databaseUser: feeds
databasePass: feeds
databaseName: uat_feeds



