appDomains: feedmachine.rorymcstay.com,uatfeedmachine.local,10.66.66.1,ui-server-svc.uat,ui-server-svc.prod,uatfeedmachine,uatfeedmachine:30000,https:uatfeedmachine:30000
databaseUrl: postgres://postgres:postgres@database-postgresql:5432/authn
authnServerPort: 3000
redis:
  password: 7MGh3jmmk0 
  user: 'authn'
  url: redis://redis-master.services.svc.cluster.local:6379/0
credentials:
  secretKeyBase: changeme
  httpUser: hello
  httpPass: world

authnReplicas: 1
authnServerImage: keratin/authn-server:1.10.0


